# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com
before:
  hooks:
    - go mod tidy
    - go generate ./...

builds:
  - id: check_dhcpv6
    main: ./cmd/check_dhcpv6
    binary: check_dhcpv6
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
  - id: check_keepalived
    main: ./cmd/check_keepalived
    binary: check_keepalived
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

nfpms:
  - package_name: monitoring-plugins-ohc
    maintainer: Jan Graichen <jan.graichen@hpi.de>
    bindir: /usr/lib/nagios/plugins
    formats:
      - deb
    contents:
      - src: contrib/check-commands.conf
        dst: /usr/share/icinga2/include/plugins-contrib.d/ohc.conf
    scripts:
      postinstall: contrib/pkg/postinstall.sh

archives:
  - format: tar.gz

checksum:
  algorithm: sha384
  name_template: SHA384SUMS

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  use: git

  groups:
    - title: Changes
      regexp: '^.*?feat(\([[:word:]]+\))??!?:.+$'
      order: 0
    - title: Fixes
      regexp: '^.*?fix(\([[:word:]]+\))??!?:.+$'
      order: 1
    - title: Others
      order: 999

  filters:
    exclude:
      - "^Merge pull request"

release:
  draft: False
